apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-web-deployment
  labels:
    app: client-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-web
  template:
    metadata:
      labels:
        app: client-web
    spec:
      containers:
      - name: client-web
        image: dongwon21/client-web:latest
        ports:
        - containerPort: 8501
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: client-web-service
spec:
  selector:
    app: client-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
